[pytest]

pythonpath = .

addopts = 
    -v
    --cov=pipeline --cov-report=html

testpaths =
    tests/unit
    tests/integration

markers =
    unit: marks tests as unit tests
    integration: marks tests as integration tests